<a href="https://colab.research.google.com/github/RajuNaik29/Python-Libraries/blob/main/Pandas_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np

In [32]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 51.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 42.9MB/s]

In [33]:
movies = pd.read_csv('movies.csv')
directors = pd.read_csv('directors.csv')

In [34]:
movies

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [35]:
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [37]:
movies = pd.read_csv('movies.csv', index_col = 0)

'''index_col=0: This is an optional parameter for the read_csv function.
It specifies that the first column of the CSV file should be used as the index (row labels) of the DataFrame.
In this case, the value is set to 0, indicating that the first column of the CSV file should be used as the index.'''


directors = pd.read_csv('directors.csv', index_col = 0)

In [38]:
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [39]:
directors

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

In [40]:
movies.shape # movies.shape

(1465, 11)

In [41]:
directors.shape # directors.shape

(2349, 3)

In [42]:
movies.head() # movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [18]:
directors.head() # directore.head()

       director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [44]:
directors['id'].nunique() #To find no . of unique directors in directors table. # directors['id'].nunique()

2349

In [20]:
movies['director_id'].nunique() #To find no . of unique directors in movies table. # movies['director_id'].nunique()

199

### **pd.isin()**

The `pd.isin()` function in Pandas is used to check whether each element in a DataFrame or Series is contained in a sequence of values. Here's an explanation of its functionality:

- **Function**: `pd.isin()`
- **Input**:
  - The values to check for containment can be specified as a list, tuple, NumPy array, or another DataFrame or Series.
- **Output**: Returns a boolean DataFrame or Series indicating whether each element is contained in the specified sequence of values.
- **Usage**:
  - Typically used when you want to filter rows or perform conditional operations based on whether values are present in a given list or array.
- **Example**:
  ```python
  import pandas as pd

  # Create a DataFrame
  df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': ['x', 'y', 'z', 'w']})

  # Check if values in column 'A' are contained in a list
  mask = df['A'].isin([2, 3, 5])

  print(mask)
  ```
  Output:
  ```
  0    False
  1     True
  2     True
  3    False
  Name: A, dtype: bool
  ```
- **Note**:
  - The `pd.isin()` function returns a boolean DataFrame or Series with the same shape as the original DataFrame or Series, where each element indicates whether the corresponding element is contained in the specified sequence of values.
  - You can use the resulting boolean array as a mask to filter rows or perform conditional operations on the DataFrame.
  - If the specified sequence of values contains NaN (missing) values, they will be treated as not contained in the original DataFrame or Series.
  - The function can be applied to a single column (Series) or an entire DataFrame by selecting the desired column(s) to check for containment.

In [45]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': ['x', 'y', 'z', 'w']})

# Check if values in column 'A' are contained in a list
mask = df['A'].isin([2, 3, 5])

print(mask)

0    False
1     True
2     True
3    False
Name: A, dtype: bool

In [50]:
# .isin() function
'''
The .isin() function in pandas is used to filter data frames.
It allows you to filter a DataFrame based on a particular column by selecting the rows where the column's values match any of a specified list or array of values.

syntax : DataFrame[DataFrame['column_name'].isin(list_of_values)]

1. DataFrame['column_name']: This is the column you want to filter on.
2. .isin(list_of_values): This function is applied to the selected column and returns a boolean Series indicating whether each element in the column is contained in the specified list of values.


'''

# small example of .isin() function

import pandas as pd

# Creating a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
        'Age': [25, 30, 35, 40, 22]}
df = pd.DataFrame(data)
print(df)

# Using .isin() to filter rows based on a list of names
selected_names = ['Bob', 'David']
filtered_df = df['Name'].isin(selected_names)

Data_frame_fdf = df[filtered_df]

print()

print(filtered_df)

print()

print(Data_frame_fdf)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

0    False
1     True
2    False
3     True
4    False
Name: Name, dtype: bool

    Name  Age
1    Bob   30
3  David   40

In [52]:
movies['director_id'].isin(directors['id']) #This will print boolean values(kind of masking)

0       True
1       True
2       True
3       True
5       True
        ...
4736    True
4743    True
4748    True
4749    True
4768    True
Name: director_id, Length: 1465, dtype: bool

In [24]:
''' It checks whether each value in the 'director_id' column is present in the 'id' column of the 'directors' DataFrame.
This operation returns a boolean Series indicating whether each 'director_id' is in the list of director IDs.'''


movies['director_id'].isin(directors['id']).value_counts()

True    1465
Name: director_id, dtype: int64

In [25]:
# in vs .isin()

'''In Python, the 'in' keyword is used as a membership test.
 It checks whether a specific value is present in a sequence (like a list, tuple, or string).
 '''

# For example:
my_list = [1, 2, 3, 4, 5]

# Using 'in' to check membership
print(3 in my_list)  # Output: True
print(6 in my_list)  # Output: False

True
False

In [53]:
np.all(movies['director_id'].isin(directors['id'])) # all the values should be True to give output as True, if any one value is false the final output will be false.

True

In [55]:
np.any(movies['director_id'].isin(directors['id'])) # If any one value is True then the final output is True.

True

In [56]:
data = pd.merge(movies,directors, left_on = 'director_id', right_on = 'id')
data.head()

# Here we got id_x and id_y, where id_x  belongs to movies 'id' column and id_y belongs to 'id' in directors table.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,4762,1997,Nov,Tuesday,James Cameron,4762,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,4762,1991,Jul,Monday,James Cameron,4762,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,4762,1994,Jul,Thursday,James Cameron,4762,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,4762,1989,Aug,Wednesday,James Cameron,4762,Male

In [57]:
data.drop(columns = ['director_id','id_y'], inplace = True)

In [58]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male

In [59]:
data.rename(columns = {'id_x' : 'movie_id'}, inplace = True)

data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [61]:
# Check wheather movies released in given list of years or not [2000, 2005,2009]

mask = data['year'].isin([2000, 2005,2009])
mask

0        True
1       False
2       False
3       False
4       False
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: year, Length: 1465, dtype: bool

In [63]:
mask.shape

(1465,)

In [66]:
data['year'].isin([2000,2005,2009]).value_counts() # This will give both True and False counts.

False    1269
True      196
Name: year, dtype: int64

In [65]:
data['year'].isin([2000,2005,2009]).sum() # This will give only count True values, because True = 1->>>(1+1+1+1+......=196) and False = 0->>>(0+0+0+0+....=0)

196

In [67]:
mask

0        True
1       False
2       False
3       False
4       False
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: year, Length: 1465, dtype: bool

In [68]:
data[mask] #This will give the 'data' DataFrame filtered for True values.

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
13,45801,20000000,14,12482775,The Weather Man,6.0,289,2005,Oct,Thursday,Gore Verbinski,Male
17,44154,72000000,32,96889998,Jarhead,6.6,765,2005,Nov,Friday,Sam Mendes,Male
19,45674,17000000,10,14899417,Away We Go,6.7,189,2009,Jun,Friday,Sam Mendes,Male
25,43716,150000000,115,374218673,Batman Begins,7.5,7359,2005,Jun,Friday,Christopher Nolan,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1408,46370,15000000,26,8459458,Chloe,5.9,498,2009,Mar,Wednesday,Atom Egoyan,Male
1421,45788,20000000,10,17436509,Capitalism: A Love Story,7.0,167,2009,Sep,Sunday,Michael Moore,Male
1432,46091,0,4,0,The White Countess,6.9,21,2005,Oct,Sunday,James Ivory,Male
1435,46858,0,1,0,The City of Your Final Destination,5.7,9,2009,Mar,Saturday,James Ivory,Male
1458,47152,4000000,42,152925093,Saw II,6.3,1251,2005,Oct,Friday,Darren Lynn Bousman,Male

In [69]:
data.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male

### **pd.apply()**

The `pd.apply()` function in Pandas is used to apply a function along an axis of a DataFrame. Here's an explanation of its functionality:

- **Function**: `pd.apply()`
- **Input**:
  - The function to apply can be a NumPy universal function (ufunc), a Python function, or a callable object.
- **Output**: Returns a Series or DataFrame resulting from applying the function along the specified axis.
- **Usage**:
  - Typically used when you want to apply a custom function to each row or column of a DataFrame, or to transform the entire DataFrame using a function.
- **Parameters**:
  - `func`: The function to apply. This can be a function or method to apply to each element of the DataFrame, or a NumPy ufunc to apply element-wise.
  - `axis`: Specifies the axis along which the function should be applied. Default is 0 (apply the function along columns). Use `axis=1` to apply the function along rows.
  - `broadcast`: If set to True, automatically aligns the input function along the specified axis before applying. Default is False.
  - `raw`: If set to True, passes each row or column as a 1D NumPy array to the function. Default is False.
  - `result_type`: Specifies the return type of the function. Options include `'expand'`, `'reduce'`, and `'broadcast'`. Default is None.
- **Example**:
  ```python
  import pandas as pd

  # Create a DataFrame
  df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

  # Define a function to double each element
  def double(x):
      return x * 2

  # Apply the function to each element of column 'A'
  result = df['A'].apply(double)

  print(result)
  ```
  Output:
  ```
  0    2
  1    4
  2    6
  Name: A, dtype: int64
  ```
- **Note**:
  - The function provided to `pd.apply()` is applied element-wise by default, meaning it's applied to each element along the specified axis.
  - The `axis` parameter specifies whether the function should be applied along rows (`axis=1`) or columns (`axis=0`) of the DataFrame.
  - The `pd.apply()` function is flexible and can be used with both simple Python functions and more complex custom functions.
  - If the function returns a Series, the result will be a DataFrame with the same index as the original DataFrame. If it returns a scalar value, the result will be a Series.

In [70]:
# About .apply() function

'''
The .apply() function in pandas is used to apply a given function along the axis of a DataFrame or Series.
It is a versatile and powerful function that allows you to transform data in a DataFrame or Series based on a specified function.

syntax : DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), **kwds)

1. func: The function to apply to each column or row.
2. axis: Specifies whether the function should be applied along rows (axis=0) or columns (axis=1). By default, it's applied to columns (axis=0).
3. raw: If True, the function receives ndarray objects instead of Series.
4. result_type: If specified, it determines the type of the result.
5. args: A tuple that contains additional positional arguments to pass to the function.
6. **kwds: Additional keyword arguments to pass to the function.
'''

#Example - 1
import pandas as pd

# Creating a sample DataFrame
table = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(table)
print(df)
print()

# Applying a function to each column
def square_column(column):
    return column ** 2

result = df.apply(square_column)
print(result)

   A  B
0  1  4
1  2  5
2  3  6

   A   B
0  1  16
1  4  25
2  9  36

In [71]:
#Example - 2
import pandas as pd

# Creating a sample Series
s = pd.Series([1, 2, 3, 4])

# Applying a function to each element in the Series
def square_element(element):
    return element ** 2

result = s.apply(square_element)
print(result)

0     1
1     4
2     9
3    16
dtype: int64

In [ ]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male

In [73]:
# Define a function to check wheather given gender is male or female. Return 0 for male and 1 for female.
def encode(gender):
  if gender == 'Male':
    return 0
  else:
    return 1

In [74]:
encode('Male')

0

In [75]:
encode('Female')

1

In [78]:
# Now lets apply encode function to the gener column of data

data['gender'].apply(encode) #data['gender'].apply(encoder)

0       0
1       0
2       0
3       0
4       0
       ..
1460    1
1461    1
1462    1
1463    1
1464    1
Name: gender, Length: 1465, dtype: int64

In [79]:
data['Male/Female'] = data['gender'].apply(encode)
data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1

In [80]:
data.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0

In [81]:
data['gender'].value_counts()

Male      1309
Female      32
Name: gender, dtype: int64

In [82]:
data['Male/Female'].value_counts()

0    1309
1     156
Name: Male/Female, dtype: int64

In [83]:
data[['revenue', 'budget']]

         revenue     budget
0     2787965087  237000000
1     1845034188  200000000
2      520000000  100000000
3      378882411  115000000
4       90000098   70000000
...          ...        ...
1460    25288872          0
1461    13368437    6500000
1462           0    3000000
1463           0          0
1464     4186931     250000

[1465 rows x 2 columns]

In [85]:
data[['revenue', 'budget']].apply(np.sum)

revenue    209866997305
budget      70353617179
dtype: int64

In [ ]:
 # .apply() will take axis = 0 as default.

# This code will aggregate all the rows present in the revenue column and all the rows in budget column.



'''The .apply() function is used here to apply the np.sum function to each column independently.
np.sum is a NumPy function that calculates the sum of elements along a specified axis.
In this case, it's being used to calculate the sum of values in Revenue column and Budget column.'''

"The .apply() function is used here to apply the np.sum function to each column independently. \nnp.sum is a NumPy function that calculates the sum of elements along a specified axis.\nIn this case, it's being used to calculate the sum of values in each column."

In [87]:
data[['revenue', 'budget']].apply(np.sum, axis = 0)

revenue    209866997305
budget      70353617179
dtype: int64

In [88]:
data[['revenue', 'budget']].apply(np.sum, axis = 1) # This will add revenue + budget of each row.

0       3024965087
1       2045034188
2        620000000
3        493882411
4        160000098
           ...
1460      25288872
1461      19868437
1462       3000000
1463             0
1464       4436931
Length: 1465, dtype: int64

In [89]:
data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1

In [90]:
# Now lets write a function for profit of the movie
def profit(movie):
  return movie['revenue'] - movie['budget']

In [91]:
profit(data.loc[0])

2550965087

In [92]:
data.apply(profit, axis = 1)

0       2550965087
1       1645034188
2        420000000
3        263882411
4         20000098
           ...
1460      25288872
1461       6868437
1462      -3000000
1463             0
1464       3936931
Length: 1465, dtype: int64

In [93]:
data['profit/loss'] = data.apply(profit, axis = 1)

In [94]:
data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1,25288872
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1,6868437
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1,-3000000
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1,0
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1,3936931

In [95]:
data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1,25288872
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1,6868437
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1,-3000000
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1,0
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1,3936931

In [96]:
# define a function to know which movie made profit and which movie made loss


def profit_loss(movie):
  if movie['profit/loss'] > 0:
    return 'Profit'
  elif movie['profit/loss'] == 0:
    return 'No profit/loss'
  else:
    return 'Loss'

In [99]:
data.apply(profit_loss, axis = 1) #data.apply(profit_loss, axis = 1)

0               Profit
1               Profit
2               Profit
3               Profit
4               Profit
             ...
1460            Profit
1461            Profit
1462              Loss
1463    No profit/loss
1464            Profit
Length: 1465, dtype: object

In [100]:
data['profit/loss/neutral'] = data.apply(profit_loss, axis = 1)

In [101]:
data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1,25288872,Profit
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1,6868437,Profit
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1,-3000000,Loss
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1,0,No profit/loss
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1,3936931,Profit

In [107]:
data.apply(profit_loss, axis = 1).value_counts()

Profit            1041
Loss               319
No profit/loss     105
dtype: int64

In [109]:
(data['profit/loss'] > 0).sum() # No of profit occured movies

1041

In [117]:
data[(data['profit/loss'] > 0)]

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,46827,0,5,188126,Repo! The Genetic Opera,6.7,100,2008,Jul,Friday,Darren Lynn Bousman,Male,0,188126,Profit
1458,47152,4000000,42,152925093,Saw II,6.3,1251,2005,Oct,Friday,Darren Lynn Bousman,Male,0,148925093,Profit
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1,25288872,Profit
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1,6868437,Profit
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1,3936931,Profit

In [114]:
(data['profit/loss'] < 0).sum() # No of movies that made loss

319

In [120]:
data[(data['profit/loss'] < 0)]

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
9,43610,255000000,49,89289910,The Lone Ranger,5.9,2311,2013,Jul,Wednesday,Gore Verbinski,Male,0,-165710090,Loss
13,45801,20000000,14,12482775,The Weather Man,6.0,289,2005,Oct,Thursday,Gore Verbinski,Male,0,-7517225,Loss
19,45674,17000000,10,14899417,Away We Go,6.7,189,2009,Jun,Friday,Sam Mendes,Male,0,-2100583,Loss
33,44561,50000000,9,0,For Love of the Game,6.3,88,1999,Sep,Friday,Sam Raimi,Male,0,-50000000,Loss
34,45111,32000000,16,18552460,The Quick and the Dead,6.3,427,1995,Feb,Thursday,Sam Raimi,Male,0,-13447540,Loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,46975,7000000,7,2062066,Auto Focus,6.1,56,2002,Oct,Friday,Paul Schrader,NaN,1,-4937934,Loss
1452,47233,5000000,6,0,Light Sleeper,5.7,15,1992,Aug,Friday,Paul Schrader,NaN,1,-5000000,Loss
1453,47263,15000000,10,0,Dying of the Light,4.5,118,2014,Dec,Thursday,Paul Schrader,NaN,1,-15000000,Loss
1454,48244,250000,6,56825,The Canyons,4.1,75,2013,Jul,Monday,Paul Schrader,NaN,1,-193175,Loss
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1,-3000000,Loss

In [123]:
(data['profit/loss'] == 0).sum() #No of no loss no gain movies

105

In [124]:
data[data['profit/loss'] == 0].head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
36,46021,0,10,0,A Simple Plan,6.9,187,1998,Dec,Friday,Sam Raimi,Male,0,0,No profit/loss
107,45166,0,9,0,Down to Earth,4.9,95,2001,Feb,Friday,Chris Weitz,NaN,1,0,No profit/loss
139,45451,0,7,0,Money Talks,5.9,87,1997,Aug,Friday,Brett Ratner,Male,0,0,No profit/loss
214,48135,0,0,0,Finishing The Game,4.9,8,2007,Jan,Sunday,Justin Lin,NaN,1,0,No profit/loss
215,48231,0,3,0,Better Luck Tomorrow,6.5,27,2002,Jan,Saturday,Justin Lin,NaN,1,0,No profit/loss

In [127]:
## about .sort_values() function

'''
The .sort_values() function in pandas is used to sort a DataFrame or Series by the values along either axis.
This function is particularly useful when you want to arrange the data in ascending or descending order based on one or more columns.

syntax : DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, ignore_index=False, key=None)

1.  by : This is the name or list of names of the columns by which to sort the DataFrame.
2.  axis : This specifies whether to sort along rows (axis=0) or columns (axis=1). The default is 0 (rows).
3.  ascending : If True, sort in ascending order; if False, sort in descending order.
4.  inplace : If True, perform the operation in place and do not return a new DataFrame.
5.  ignore_index : If True, the resulting DataFrame will have a new index.
6.  key : A function to extract a comparison key from each element of the column by which to sort.

'''

import pandas as pd

# Creating a sample DataFrame
table = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 35],
        'Salary': [50000, 60000, 45000, 70000]}

df = pd.DataFrame(table)

sorted_df_age = df.sort_values(by='Age', ascending=True)
sorted_df_Name = df.sort_values(by='Name', ascending=True)
sorted_df_Salary = df.sort_values(by = 'Salary', ascending = True)
print(sorted_df_age)
print()
print(sorted_df_Name)
print()
print(sorted_df_Salary)

      Name  Age  Salary
2  Charlie   22   45000
0    Alice   25   50000
1      Bob   30   60000
3    David   35   70000

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000
3    David   35   70000

      Name  Age  Salary
2  Charlie   22   45000
0    Alice   25   50000
1      Bob   30   60000
3    David   35   70000

In [128]:
data.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit

In [130]:
data.sort_values(by = 'popularity', ascending = False).head() # we can give ascending = True/1 or False/0 (default = false)

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
23,43692,165000000,724,675120017,Interstellar,8.1,10867,2014,Nov,Wednesday,Christopher Nolan,Male,0,510120017,Profit
361,43724,150000000,434,378858340,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male,0,228858340,Profit
11,43796,140000000,271,655011224,Pirates of the Caribbean: The Curse of the Bla...,7.5,6985,2003,Jul,Wednesday,Gore Verbinski,Male,0,515011224,Profit
315,43797,125000000,206,752100229,The Hunger Games: Mockingjay - Part 1,6.6,5584,2014,Nov,Tuesday,Francis Lawrence,Male,0,627100229,Profit
22,43662,185000000,187,1004558444,The Dark Knight,8.2,12002,2008,Jul,Wednesday,Christopher Nolan,Male,0,819558444,Profit

In [131]:
data.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit

In [132]:
# In which year did the most of the movies release

data['year'].value_counts().head()

2006    73
2005    71
2002    69
2008    67
2011    67
Name: year, dtype: int64

### **pd.groupby()**

The `pd.groupby()` function in Pandas is used to group the rows of a DataFrame based on one or more columns, and then perform aggregation or other operations on these groups. Here's an explanation of its functionality:

- **Function**: `pd.groupby()`
- **Input**:
  - The column or columns to group by.
- **Output**: Returns a GroupBy object, which is a special DataFrameGroupBy object that represents the grouped data.
- **Usage**:
  - Typically used when you want to perform operations on subsets of data based on some categorical variable(s).
- **Parameters**:
  - `by`: Specifies the column or columns to group by. It can be a single column name, a list of column names, or a dictionary mapping column names to group keys.
  - `axis`: Specifies the axis along which to group. Default is 0 (rows).
  - `level`: If the axis is a MultiIndex (hierarchical index), specifies the level(s) to group by.
  - `sort`: Specifies whether to sort the resulting groups by the group keys. Default is True.
  - Other parameters such as `as_index`, `group_keys`, and `squeeze` control various aspects of the group operation.
- **Example**:
  ```python
  import pandas as pd

  # Create a DataFrame
  df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar'],
                     'B': ['one', 'one', 'two', 'two'],
                     'C': [1, 2, 3, 4]})

  # Group the DataFrame by column 'A'
  grouped = df.groupby('A')

  # Calculate the mean of column 'C' for each group
  mean_values = grouped['C'].mean()

  print(mean_values)
  ```
  Output:
  ```
  A
  bar    3.0
  foo    2.0
  Name: C, dtype: float64
  ```
- **Note**:
  - `pd.groupby()` does not actually perform any computation until an aggregation function (e.g., `sum()`, `mean()`, `count()`) is applied to the GroupBy object.
  - The resulting GroupBy object can be used to apply various aggregation functions, such as `sum()`, `mean()`, `count()`, `max()`, `min()`, `agg()`, etc., to compute summary statistics for each group.
  - Grouping can be performed on a single column, multiple columns, or even on levels of a MultiIndex.

In [133]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar'],
                   'B': ['one', 'one', 'two', 'two'],
                   'C': [1, 2, 3, 4]})

print(df)

     A    B  C
0  foo  one  1
1  bar  one  2
2  foo  two  3
3  bar  two  4

In [134]:
# Group the DataFrame by column 'A'
grouped = df.groupby('A')

# Calculate the mean of column 'C' for each group
mean_values = grouped['C'].mean()

print(mean_values)

A
bar    3.0
foo    2.0
Name: C, dtype: float64

In [135]:
# about groupby() function

'''
The groupby() function in pandas is used for grouping rows of a DataFrame based on some criterion.
It is a powerful and flexible tool for data analysis and manipulation. The groupby() operation involves the following steps:

Process of groupby in pandas
1. Splitting : The data is divided into groups based on a specified criterion.
2. Applying a function : A function is applied to each group independently.
3. Combining results : The results are combined into a new data structure.


syntax : DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, observed=False, **kwargs)


1. by : This can be a column name, a list of column names, a function, or a dictionary. It determines how the DataFrame should be grouped.
2. axis : Specifies whether the grouping should be done along rows (axis=0) or columns (axis=1).
3. level : If the axis is a MultiIndex, this parameter specifies the level(s) to use for grouping.
4. as_index : If True, the group labels will be used as index. If False, they will be added as new columns.
5. sort : If True, the groups are sorted. If False, the order is the same as the original.
6. group_keys : If True, include group keys in the index (if as_index=True) or as new columns (if as_index=False).
7. squeeze : If True, return a Series if the resulting DataFrame has a single column.
8. observed : If True, it will only show observed values for categorical groupers. This is relevant for categorical data types.


'''

import pandas as pd

table = {
    'Movie': ['Movie1', 'Movie2', 'Movie3', 'Movie4', 'Movie5'],
    'Genre': ['Action', 'Comedy', 'Action', 'Comedy', 'Action'],
    'Rating': [8, 7, 9, 6, 8]
}

df = pd.DataFrame(table)

df

    Movie   Genre  Rating
0  Movie1  Action       8
1  Movie2  Comedy       7
2  Movie3  Action       9
3  Movie4  Comedy       6
4  Movie5  Action       8

In [136]:
# Grouping by the 'Genre' column
grouped = df.groupby('Genre')
print(grouped)
print()

# Applying a function (e.g., calculating the mean) to each group
mean_ratings = grouped['Rating'].mean()
sum_ratings = grouped['Rating'].sum()
max_rating = grouped['Rating'].max()
min_rating = grouped['Rating'].min()
count_ratings = grouped['Rating'].count()


print('average of ratings = ',mean_ratings)
print()
print('sum of ratings = ',sum_ratings)
print()
print('Maximum rating = ',max_rating)
print()
print('Minimum rating = ',min_rating)
print()
print('Count of Ratings = ',count_ratings)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x78c1655ae080>

average of ratings =  Genre
Action    8.333333
Comedy    6.500000
Name: Rating, dtype: float64

sum of ratings =  Genre
Action    25
Comedy    13
Name: Rating, dtype: int64

Maximum rating =  Genre
Action    9
Comedy    7
Name: Rating, dtype: int64

Minimum rating =  Genre
Action    8
Comedy    6
Name: Rating, dtype: int64

Count of Ratings =  Genre
Action    3
Comedy    2
Name: Rating, dtype: int64

In [139]:
data.groupby('director_name')

In [140]:
data.groupby('director_name').ngroups

'''.ngroups: This attribute of the groupby object returns the number of groups that were formed based on the grouping criterion.
In this case, it counts the number of unique director names in the 'director_name' column.

'''


data.groupby('director_name').ngroups

199

In [143]:
'''.groups: This attribute of the groupby object returns a dictionary where the keys are the unique values in the 'director_name' column,
 and the values are the corresponding indices (row numbers) of the rows in each group.'''
data.groupby('director_name').groups

{'Adam McKay': [635, 636, 637, 638, 639, 640], 'Adam Shankman': [792, 793, 794, 795, 796, 797, 798, 799], 'Alejandro González Iñárritu': [465, 466, 467, 468, 469, 470], 'Alex Proyas': [425, 426, 427, 428, 429], 'Alexander Payne': [1341, 1342, 1343, 1344, 1345], 'Andrew Adamson': [63, 64, 65, 66, 67], 'Andrew Niccol': [1177, 1178, 1179, 1180, 1181], 'Andrzej Bartkowiak': [913, 914, 915, 916, 917], 'Andy Fickman': [1152, 1153, 1154, 1155, 1156, 1157], 'Andy Tennant': [883, 884, 885, 886, 887, 888], 'Ang Lee': [441, 442, 443, 444, 445, 446, 447, 448], 'Anne Fletcher': [1262, 1263, 1264, 1265, 1266], 'Antoine Fuqua': [856, 857, 858, 859, 860, 861, 862, 863], 'Atom Egoyan': [1405, 1406, 1407, 1408, 1409, 1410], 'Barry Levinson': [870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882], 'Barry Sonnenfeld': [73, 74, 75, 76, 77, 78, 79], 'Ben Stiller': [721, 722, 723, 724, 725], 'Bill Condon': [454, 455, 456, 457, 458], 'Bobby Farrelly': [918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928], 'Brad Anderson': [1439, 1440, 1441, 1442, 1443], 'Brett Ratner': [131, 132, 133, 134, 135, 136, 137, 138, 139], 'Brian De Palma': [740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751], 'Brian Helgeland': [1141, 1142, 1143, 1144, 1145], 'Brian Levant': [1017, 1018, 1019, 1020, 1021, 1022], 'Brian Robbins': [1011, 1012, 1013, 1014, 1015, 1016], 'Bryan Singer': [47, 48, 49, 50, 51, 52, 53, 54], 'Cameron Crowe': [902, 903, 904, 905, 906, 907], 'Catherine Hardwicke': [1256, 1257, 1258, 1259, 1260, 1261], 'Chris Columbus': [493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503], 'Chris Weitz': [105, 106, 107, 108, 109, 110], 'Christopher Nolan': [21, 22, 23, 24, 25, 26, 27, 28], 'Chuck Russell': [641, 642, 643, 644, 645, 646], 'Clint Eastwood': [934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952], 'Curtis Hanson': [1105, 1106, 1107, 1108, 1109, 1110, 1111], 'Danny Boyle': [1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176], 'Darren Aronofsky': [487, 488, 489, 490, 491, 492], 'Darren Lynn Bousman': [1455, 1456, 1457, 1458, 1459], 'David Ayer': [277, 278, 279, 280, 281, 282], 'David Cronenberg': [1199, 1200, 1201, 1202, 1203, 1204, 1205], 'David Fincher': [302, 303, 304, 305, 306, 307, 308, 309, 310, 311], 'David Gordon Green': [1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213], 'David Koepp': [1068, 1069, 1070, 1071, 1072], 'David Lynch': [1239, 1240, 1241, 1242, 1243], 'David O. Russell': [1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030], 'David R. Ellis': [1234, 1235, 1236, 1237, 1238], 'David Zucker': [1229, 1230, 1231, 1232, 1233], 'Dennis Dugan': [726, 727, 728, 729, 730, 731, 732, 733, 734], 'Donald Petrie': [1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051], 'Doug Liman': [290, 291, 292, 293, 294, 295, 296], 'Edward Zwick': [418, 419, 420, 421, 422, 423, 424], 'F. Gary Gray': [848, 849, 850, 851, 852, 853, 854, 855], 'Francis Ford Coppola': [1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104], 'Francis Lawrence': [312, 313, 314, 315, 316], 'Frank Coraci': [600, 601, 602, 603, 604, 605, 606], 'Frank Oz': [680, 681, 682, 683, 684, 685, 686], 'Garry Marshall': [894, 895, 896, 897, 898, 899, 900, 901], 'Gary Fleder': [1158, 1159, 1160, 1161, 1162, 1163], 'Gary Winick': [787, 788, 789, 790, 791], 'Gavin O'Connor': [1369, 1370, 1371, 1372, 1373], 'George A. Romero': [774, 775, 776, 777, 778, 779], 'George Clooney': [908, 909, 910, 911, 912], 'George Miller': [361, 362, 363, 364, 365, 366, 367], 'Gore Verbinski': [7, 8, 9, 10, 11, 12, 13], 'Guillermo del Toro': [180, 181, 182, 183, 184], 'Gus Van Sant': [1244, 1245, 1246, 1247, 1248, 1249, 1250], 'Guy Ritchie': [510, 511, 512, 513, 514, 515, 516], 'Harold Ramis': [1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043], 'Ivan Reitman': [805, 806, 807, 808, 809, 810, 811, 812], 'James Cameron': [0, 1, 2, 3, 4, 5, 6], 'James Ivory': [1432, 1433, 1434, 1435, 1436, 1437, 1438], 'James Mangold': [559, 560, 561, 562, 563, 564, 565, 566], 'James Wan': [166, 167, 168, 169, 170, 171, 172], 'Jan de Bont': [595, 596, 597, 598, 599], 'Jason Friedberg': [1364, 1365, 1366, 1367, 1368], 'Jason Reitman': [1336, 1337, 1338, 1339, 1340], 'Jaume Collet-Serra': [1146, 1147, 1148, 1149, 1150, 1151], 'Jay Roach': [687, 688, 689, 690, 691, 692, 693, 694], 'Jean-Pierre Jeunet': [1031, 1032, 1033, 1034, 1035], 'Joe Dante': [830, 831, 832, 833, 834, 835], 'Joe Wright': [402, 403, 404, 405, 406, 407], 'Joel Coen': [1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062], 'Joel Schumacher': [532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544], 'John Carpenter': [1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191], 'John Glen': [1251, 1252, 1253, 1254, 1255], 'John Landis': [1164, 1165, 1166, 1167, 1168], 'John Madden': [1086, 1087, 1088, 1089, 1090], 'John McTiernan': [522, 523, 524, 525, 526, 527, 528, 529, 530, 531], 'John Singleton': [836, 837, 838, 839, 840, 841, 842], 'John Whitesell': [1112, 1113, 1114, 1115, 1116], 'John Woo': [545, 546, 547, 548, 549, 550, 551], 'Jon Favreau': [243, 244, 245, 246, 247, 248], 'Jon M. Chu': [449, 450, 451, 452, 453], 'Jon Turteltaub': [317, 318, 319, 320, 321, 322, 323], 'Jonathan Demme': [819, 820, 821, 822, 823], 'Jonathan Liebesman': [388, 389, 390, 391, 392], 'Judd Apatow': [889, 890, 891, 892, 893], 'Justin Lin': [211, 212, 213, 214, 215], 'Kenneth Branagh': [381, 382, 383, 384, 385, 386, 387], 'Kenny Ortega': [1006, 1007, 1008, 1009, 1010], 'Kevin Reynolds': [297, 298, 299, 300, 301], ...}

In [144]:
'''.get_group('Adam McKay'): Retrieves a specific group based on the value provided, in this case, the director's name 'Adam McKay'.
 It returns a DataFrame containing only the rows associated with the specified group.'''

data.groupby('director_name').get_group('Adam McKay')

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
635,43882,100000000,24,170432927,The Other Guys,6.1,1383,2010,Aug,Friday,Adam McKay,Male,0,70432927,Profit
636,44151,72500000,12,162966177,Talladega Nights: The Ballad of Ricky Bobby,6.2,491,2006,Aug,Friday,Adam McKay,Male,0,90466177,Profit
637,44236,65000000,22,128107642,Step Brothers,6.5,1062,2008,Jul,Friday,Adam McKay,Male,0,63107642,Profit
638,44503,50000000,38,173649015,Anchorman 2: The Legend Continues,6.0,923,2013,Dec,Wednesday,Adam McKay,Male,0,123649015,Profit
639,45301,28000000,57,133346506,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,Male,0,105346506,Profit
640,45443,26000000,29,90574188,Anchorman: The Legend of Ron Burgundy,6.7,1493,2004,Jul,Friday,Adam McKay,Male,0,64574188,Profit

In [146]:
data.groupby('director_name').count() # count of all columns the director directed.

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,gender,Male/Female,profit/loss,profit/loss/neutral
director_name,,,,,,,,,,,,,,
Adam McKay,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Adam Shankman,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alejandro González Iñárritu,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Alex Proyas,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Alexander Payne,5,5,5,5,5,5,5,5,5,5,0,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wes Craven,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Wolfgang Petersen,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Woody Allen,18,18,18,18,18,18,18,18,18,18,18,18,18,18
Zack Snyder,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Zhang Yimou,6,6,6,6,6,6,6,6,6,6,6,6,6,6

In [147]:
data['director_name'].value_counts()

Steven Spielberg      26
Martin Scorsese       19
Clint Eastwood        19
Woody Allen           18
Ridley Scott          16
                      ..
Tim Hill               5
Jonathan Liebesman     5
Roman Polanski         5
Larry Charles          5
Nicole Holofcener      5
Name: director_name, Length: 199, dtype: int64

In [148]:
data.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit

In [149]:
data.groupby('director_name').mean()

<ipython-input-149-2544c483bcfc>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('director_name').mean()

,movie_id,budget,popularity,revenue,vote_average,vote_count,year,Male/Female,profit/loss
director_name,,,,,,,,,
Adam McKay,44586.000000,5.691667e+07,30.333333,1.431794e+08,6.466667,1326.500000,2009.333333,0.0,8.626274e+07
Adam Shankman,44821.250000,4.837500e+07,23.125000,1.091953e+08,6.037500,623.875000,2005.375000,0.0,6.082035e+07
Alejandro González Iñárritu,45660.500000,3.333333e+07,47.000000,1.463300e+08,7.233333,2286.000000,2008.000000,0.0,1.129966e+08
Alex Proyas,44477.000000,7.040000e+07,53.200000,1.549125e+08,6.480000,1667.400000,2004.200000,0.0,8.451249e+07
Alexander Payne,46025.000000,1.560000e+07,24.800000,8.204699e+07,6.880000,536.000000,2005.800000,1.0,6.644699e+07
...,...,...,...,...,...,...,...,...,...
Wes Craven,45503.300000,2.338000e+07,22.300000,7.647943e+07,5.950000,630.500000,1999.700000,0.0,5.309943e+07
Wolfgang Petersen,44511.285714,9.014286e+07,35.857143,2.307166e+08,6.571429,986.714286,1995.285714,0.0,1.405737e+08
Woody Allen,46083.777778,1.177778e+07,17.722222,3.449480e+07,6.672222,504.111111,2001.611111,0.0,2.271702e+07
Zack Snyder,44086.857143,1.228571e+08,71.857143,3.537425e+08,6.485714,3501.857143,2009.857143,0.0,2.308853e+08
Zhang Yimou,45630.166667,2.083335e+07,12.000000,6.092830e+07,6.616667,254.333333,2007.666667,0.0,4.009495e+07

In [151]:
'''
1. data.groupby('director_name'): This part of the code groups the DataFrame data by the unique values in the 'director_name' column.
It creates a groupby object.


2. .aggregate({'year': ['min', 'max'], 'vote_average': 'mean'}): The aggregate() function is applied to the groupby object to calculate summary statistics for each group.
It takes a dictionary where the keys are the column names, and the values are the aggregation functions to apply.

    a. For the 'year' column, it calculates both the minimum and maximum values using the functions 'min' and 'max'.
    b. For the 'vote_average' column, it calculates the mean using the 'mean' function.'''

data.groupby('director_name').aggregate({'year' : ['min','max'], 'vote_average' : 'mean'}) #data.groupby('director_name').agg({'year' : ['min','max'], 'vote_average' : 'mean'})

                             year       vote_average
                              min   max         mean
director_name
Adam McKay                   2004  2015     6.466667
Adam Shankman                2001  2012     6.037500
Alejandro González Iñárritu  2000  2015     7.233333
Alex Proyas                  1994  2016     6.480000
Alexander Payne              1999  2013     6.880000
...                           ...   ...          ...
Wes Craven                   1984  2011     5.950000
Wolfgang Petersen            1981  2006     6.571429
Woody Allen                  1977  2013     6.672222
Zack Snyder                  2004  2016     6.485714
Zhang Yimou                  2002  2014     6.616667

[199 rows x 3 columns]

In [152]:
# we can also use .agg()


data.groupby('director_name').agg({'year' : ['min', 'max'], 'vote_average' : 'mean', 'vote_count' : 'count'})

                             year       vote_average vote_count
                              min   max         mean      count
director_name
Adam McKay                   2004  2015     6.466667          6
Adam Shankman                2001  2012     6.037500          8
Alejandro González Iñárritu  2000  2015     7.233333          6
Alex Proyas                  1994  2016     6.480000          5
Alexander Payne              1999  2013     6.880000          5
...                           ...   ...          ...        ...
Wes Craven                   1984  2011     5.950000         10
Wolfgang Petersen            1981  2006     6.571429          7
Woody Allen                  1977  2013     6.672222         18
Zack Snyder                  2004  2016     6.485714          7
Zhang Yimou                  2002  2014     6.616667          6

[199 rows x 4 columns]

In [173]:
# show the details of all the movies directed by a "High budget director"

# high budget directors : who have atleast 1 movie budget>=100M


# step - 1 : max budget per director

director_max_bud = data.groupby('director_name')['budget'].max().reset_index() # data.groupby('director_name')['budget'].max().reset_index()
director_max_bud

                   director_name     budget
0                     Adam McKay  100000000
1                  Adam Shankman   80000000
2    Alejandro González Iñárritu  135000000
3                    Alex Proyas  140000000
4                Alexander Payne   30000000
..                           ...        ...
194                   Wes Craven   40000000
195            Wolfgang Petersen  175000000
196                  Woody Allen   30000000
197                  Zack Snyder  250000000
198                  Zhang Yimou   94000000

[199 rows x 2 columns]

In [174]:
director_max_bud['director_name'].count()

199

In [175]:
# step2: find the names of high budget directors

high_bud_directors = director_max_bud[director_max_bud['budget'] >= 100000000]['director_name']
high_bud_directors

0                       Adam McKay
2      Alejandro González Iñárritu
3                      Alex Proyas
5                   Andrew Adamson
10                         Ang Lee
                  ...
187                    Tom Shadyac
188                     Tom Tykwer
189                     Tony Scott
195              Wolfgang Petersen
197                    Zack Snyder
Name: director_name, Length: 85, dtype: object

In [176]:
high_bud_directors.count()

85

In [177]:
data.shape

(1465, 15)

In [180]:
# step3: extract the info of movies where the director is in the list of high  budget directors

data[data['director_name'].isin(high_bud_directors)]

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,44255,45000000,42,73762516,Death Race,6.0,1175,2008,Aug,Friday,Paul W.S. Anderson,Male,0,28762516,Profit
758,44367,60000000,29,26673242,Event Horizon,6.5,742,1997,Aug,Friday,Paul W.S. Anderson,Male,0,-33326758,Loss
759,44396,60000000,2,300228084,Resident Evil: Afterlife,5.8,1363,2010,Sep,Thursday,Paul W.S. Anderson,Male,0,240228084,Profit
760,44992,33000000,40,102984862,Resident Evil,6.4,2065,2002,Mar,Friday,Paul W.S. Anderson,Male,0,69984862,Profit
761,45697,18000000,16,122195920,Mortal Kombat,5.4,442,1995,Aug,Friday,Paul W.S. Anderson,Male,0,104195920,Profit

In [179]:
data[mask] # All movies of high budget are extracted.

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,44255,45000000,42,73762516,Death Race,6.0,1175,2008,Aug,Friday,Paul W.S. Anderson,Male,0,28762516,Profit
758,44367,60000000,29,26673242,Event Horizon,6.5,742,1997,Aug,Friday,Paul W.S. Anderson,Male,0,-33326758,Loss
759,44396,60000000,2,300228084,Resident Evil: Afterlife,5.8,1363,2010,Sep,Thursday,Paul W.S. Anderson,Male,0,240228084,Profit
760,44992,33000000,40,102984862,Resident Evil,6.4,2065,2002,Mar,Friday,Paul W.S. Anderson,Male,0,69984862,Profit
761,45697,18000000,16,122195920,Mortal Kombat,5.4,442,1995,Aug,Friday,Paul W.S. Anderson,Male,0,104195920,Profit

### **pd.filter()**

The `pd.filter()` function in Pandas is used to subset or filter a DataFrame based on specific criteria. Here's an explanation of its functionality:

- **Function**: `pd.filter()`
- **Input**:
  - `items`: Specifies the labels (columns or index names) to include or exclude from the result.
  - `like`: Specifies a string or regular expression to match in the column or index names.
  - `regex`: Specifies a regular expression to match in the column or index names.
  - `axis`: Specifies the axis along which to filter. Default is 0 (filter along rows).
- **Output**: Returns a new DataFrame containing only the columns or index levels that match the specified criteria.
- **Usage**:
  - Typically used when you want to select a subset of columns or index levels based on their names or labels.
- **Parameters**:
  - `items`: Specifies the labels (columns or index names) to include or exclude from the result.
  - `like`: Specifies a string or regular expression to match in the column or index names.
  - `regex`: Specifies a regular expression to match in the column or index names.
  - `axis`: Specifies the axis along which to filter. Default is 0 (filter along rows).
- **Example**:
  ```python
  import pandas as pd

  # Create a DataFrame
  df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})

  # Filter columns that contain 'A' in the column name
  filtered_df = df.filter(like='A')

  print(filtered_df)
  ```
  Output:
  ```
     A
  0  1
  1  2
  2  3
  ```
- **Note**:
  - The `pd.filter()` function can be used to select columns based on their names or labels using the `items`, `like`, or `regex` parameters.
  - If the `like` parameter is specified, it matches column or index names containing the specified string or regular expression.
  - If the `regex` parameter is specified, it matches column or index names using the specified regular expression pattern.
  - By default, the `pd.filter()` function filters along rows (axis=0). You can specify `axis=1` to filter along columns.

In [166]:
# about .filter() function.


'''
The .filter() function in pandas is used to subset the rows or columns of a DataFrame based on a particular criterion.
It allows you to include or exclude elements from a DataFrame based on a specified condition.

syntax : DataFrame.filter(items=None, like=None, regex=None, axis=None)

1. items: Specifies the columns to include/exclude by name.
2. like: Specifies the columns to include/exclude by substring.
3. regex: Specifies the columns to include/exclude by regular expression.
4. axis: Specifies whether to filter rows (axis=0) or columns (axis=1).

'''


#Example - 1
import pandas as pd

# Creating a sample DataFrame
table = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}

df = pd.DataFrame(table, index=['A', 'B', 'C'])
print(df)
print()

# Filtering rows where 'Age' is greater than 30
filtered_rows = df.filter(like='B', axis=0)

print(filtered_rows)

      Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   35   70000

  Name  Age  Salary
B  Bob   30   60000

In [167]:
# Example = 2 (axis = 1)


import pandas as pd

# Creating a sample DataFrame
table = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}

df = pd.DataFrame(table, index=['A', 'B', 'C'])
print(df)
print()

# Filtering rows where 'Age' is greater than 30
filtered_rows = df.filter(like='Age', axis=1)

print(filtered_rows)

      Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   35   70000

   Age
A   25
B   30
C   35

In [190]:
def highBudget(group):
    return group['budget'].max()>= 100000000

In [192]:
data.groupby('director_name').filter(highBudget)

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,44255,45000000,42,73762516,Death Race,6.0,1175,2008,Aug,Friday,Paul W.S. Anderson,Male,0,28762516,Profit
758,44367,60000000,29,26673242,Event Horizon,6.5,742,1997,Aug,Friday,Paul W.S. Anderson,Male,0,-33326758,Loss
759,44396,60000000,2,300228084,Resident Evil: Afterlife,5.8,1363,2010,Sep,Thursday,Paul W.S. Anderson,Male,0,240228084,Profit
760,44992,33000000,40,102984862,Resident Evil,6.4,2065,2002,Mar,Friday,Paul W.S. Anderson,Male,0,69984862,Profit
761,45697,18000000,16,122195920,Mortal Kombat,5.4,442,1995,Aug,Friday,Paul W.S. Anderson,Male,0,104195920,Profit

In [193]:
# risky? yes or no?
# director avg budget -> y
# movie budget > y

In [194]:
data.groupby('director_name')['budget'].mean()

director_name
Adam McKay                     5.691667e+07
Adam Shankman                  4.837500e+07
Alejandro González Iñárritu    3.333333e+07
Alex Proyas                    7.040000e+07
Alexander Payne                1.560000e+07
                                   ...
Wes Craven                     2.338000e+07
Wolfgang Petersen              9.014286e+07
Woody Allen                    1.177778e+07
Zack Snyder                    1.228571e+08
Zhang Yimou                    2.083335e+07
Name: budget, Length: 199, dtype: float64

### **pd.apply()**

The `pd.apply()` function in Pandas is used to apply a function along an axis of a DataFrame or Series. It can be used to perform operations on rows or columns, or to transform the entire DataFrame or Series using a custom function. Here's an explanation of its functionality:

- **Function**: `pd.apply()`
- **Input**:
  - The function to apply, which can be a NumPy universal function (ufunc), a Python function, or a callable object.
- **Output**: Returns a DataFrame or Series resulting from applying the function along the specified axis.
- **Usage**:
  - Typically used when you want to apply a custom function to each row or column of a DataFrame, or to transform the entire DataFrame or Series using a function.
- **Parameters**:
  - `func`: The function to apply. This can be a function or method to apply to each element of the DataFrame or Series, or a NumPy ufunc to apply element-wise.
  - `axis`: Specifies the axis along which the function should be applied. Default is 0 (apply the function along columns). Use `axis=1` to apply the function along rows.
  - `broadcast`: If set to True, automatically aligns the input function along the specified axis before applying. Default is False.
  - `raw`: If set to True, passes each row or column as a 1D NumPy array to the function. Default is False.
  - `result_type`: Specifies the return type of the function. Options include `'expand'`, `'reduce'`, and `'broadcast'`. Default is None.
- **Example**:
  ```python
  import pandas as pd

  # Create a DataFrame
  df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

  # Define a function to double each element
  def double(x):
      return x * 2

  # Apply the function to each element of column 'A'
  result = df['A'].apply(double)

  print(result)
  ```
  Output:
  ```
  0    2
  1    4
  2    6
  Name: A, dtype: int64
  ```
- **Note**:
  - The function provided to `pd.apply()` is applied element-wise by default, meaning it's applied to each element along the specified axis.
  - The `axis` parameter specifies whether the function should be applied along rows (`axis=1`) or columns (`axis=0`) of the DataFrame.
  - The `pd.apply()` function is flexible and can be used with both simple Python functions and more complex custom functions.
  - If the function returns a Series, the result will be a DataFrame with the same index as the original DataFrame. If it returns a scalar value, the result will be a Series.

In [195]:
def risky(group):
    group['risky'] = group['budget'] - group['budget'].mean() >=0
    return group

In [200]:
data = data.groupby('director_name').apply(risky)
data

<ipython-input-200-c5be7226c9b2>:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  data = data.groupby('director_name').apply(risky)

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral,risky
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit,True
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit,True
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit,False
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit,True
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1,25288872,Profit,False
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1,6868437,Profit,True
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1,-3000000,Loss,True
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1,0,No profit/loss,False
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1,3936931,Profit,False

In [201]:
data

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral,risky
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit,True
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit,True
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit,False
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit,True
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female,1,25288872,Profit,False
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female,1,6868437,Profit,True
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female,1,-3000000,Loss,True
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female,1,0,No profit/loss,False
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female,1,3936931,Profit,False

In [202]:
data['risky'].count()

1465

In [203]:
mask = data['director_name'] == 'James Cameron'
mask

0        True
1        True
2        True
3        True
4        True
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: director_name, Length: 1465, dtype: bool

In [204]:
data[mask]

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral,risky
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit,True
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit,True
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit,False
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit,True
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit,False
5,46000,18500000,67,183316455,Aliens,7.7,3220,1986,Jul,Friday,James Cameron,Male,0,164816455,Profit,False
6,47036,6400000,74,78371200,The Terminator,7.3,4128,1984,Oct,Friday,James Cameron,Male,0,71971200,Profit,False

In [205]:
data[mask]['budget'].mean()

106700000.0

In [206]:
data.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,Male/Female,profit/loss,profit/loss/neutral,risky
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,0,2550965087,Profit,True
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male,0,1645034188,Profit,True
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male,0,420000000,Profit,False
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male,0,263882411,Profit,True
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male,0,20000098,Profit,False

In [207]:
table = {'Name': ['Alice', 'Bob', None, 'David', 'Emma'],
        'Age': [25, 30, None, 40, 22]}

df = pd.DataFrame(table)
print(df)
print()

    Name   Age
0  Alice  25.0
1    Bob  30.0
2   None   NaN
3  David  40.0
4   Emma  22.0

In [208]:
#Given a function 'is_null' with the following implementation.

import pandas as pd

# Creating a sample DataFrame
table = {'Name': ['Alice', 'Bob', None, 'David', 'Emma'],
        'Age': [25, 30, None, 40, 22]}

df = pd.DataFrame(table)
print(df)
print()

print(missing_values)
print()

def is_null(x):
   return sum(x.isnull())
#Choose the correct statement for a dataframe 'df' when we execute the following code:

df.apply(is_null, axis=1)

    Name   Age
0  Alice  25.0
1    Bob  30.0
2   None   NaN
3  David  40.0
4   Emma  22.0

NameError: name 'missing_values' is not defined

In [210]:
# about .isnull() function
'''
The .isnull() function in pandas is used to detect missing or NaN (Not a Number) values in a DataFrame.
It returns a DataFrame or Series of the same shape as the input,
where each element is a Boolean value indicating whether the corresponding element in the original DataFrame is missing (True) or not (False).


syntax = DataFrame.isnull()


'''

import pandas as pd

# Creating a sample DataFrame
table = {'Name': ['Alice', 'Bob', None, 'David', 'Emma'],
        'Age': [25, 30, None, 40, 22]}

df = pd.DataFrame(table)
print(df)
print()

# Checking for missing values in the DataFrame
missing_values = df.isnull()

print(missing_values)

    Name   Age
0  Alice  25.0
1    Bob  30.0
2   None   NaN
3  David  40.0
4   Emma  22.0

    Name    Age
0  False  False
1  False  False
2   True   True
3  False  False
4  False  False

In [211]:
import pandas as pd

table = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df = pd.DataFrame(table)
df

     name         username  userid
0     Jim       itsjimhere      20
1  Clarke         clark002      10
2    Kent      itskentment      86
3    Mark  markyoumustknow      21

In [ ]:
def check(name,username):
    return name.lower() in username

df[~(df.apply(lambda df:check(df['name'],df['username']), axis=1))]['userid']

1    10
Name: userid, dtype: int64

In [212]:
import pandas as pd

xyz = {
    'roll_no': [1, 2, 1, 3, 1, 3, 3, 3, 2, 2, 1, 2],
    'subject': ['NN', 'DL', 'ML', 'Prob', 'DL', 'ML', 'DL', 'NN', 'NN', 'Prob', 'Prob', 'ML'],
    'marks': [97, 63, 63, 71, 64, 90, 66, 46, 74, 62, 94, 67]
}

df = pd.DataFrame(xyz)
df

    roll_no subject  marks
0         1      NN     97
1         2      DL     63
2         1      ML     63
3         3    Prob     71
4         1      DL     64
5         3      ML     90
6         3      DL     66
7         3      NN     46
8         2      NN     74
9         2    Prob     62
10        1    Prob     94
11        2      ML     67

In [ ]:
import pandas as pd

def get_marks(df):
    '''
    INPUT: df -> dataframe

    OUTPUT: result -> dataframe
    '''

    ### STEP 1: group the df using subject and get max marks

    max_marks = df.groupby("subject")["marks"].aggregate("max")

    ### STEP 2: reset the index

    max_marks = max_marks.reset_index()


    ### STEP 3: merge with original df to get roll id

    result = df.merge(max_marks,how="inner",on = ["subject","marks"])[["subject","marks","roll_no"]].sort_values("subject").reset_index(drop=True)

    return result
get_marks(df = pd.DataFrame(xyz))

  subject  marks  roll_no
0      DL     66        3
1      ML     90        3
2      NN     97        1
3    Prob     94        1

In [ ]:
import pandas as pd
a = pd.DataFrame({'name':["Ram","Shyam","Mukesh","Suresh"],'age':[10,18,60,50]})
a

     name  age
0     Ram   10
1   Shyam   18
2  Mukesh   60
3  Suresh   50

In [ ]:
def replace_ages(a):
  if a['age'] < 18:
    return 'kid'
  elif a['age'] >= 18 and a['age'] <= 50:
    return 'adult'
  else:
    return 'senior'

In [ ]:
a.apply(replace_ages, axis = 1)

0       kid
1     adult
2    senior
3     adult
dtype: object

In [ ]:

import pandas as pd

std = {
    'name': ['Luffy', 'Chopper', 'Zoro', 'Sanji'],
    'marks': [15, 89, 33, 32]
}

df = pd.DataFrame(std)
df

      name  marks
0    Luffy     15
1  Chopper     89
2     Zoro     33
3    Sanji     32

In [ ]:
import pandas as pd

def filter(df, k):
    '''
    INPUT:
        df -> dataframe
        k -> cutoff (int)

    OUTPUT:
        result -> dataframe
    '''

    ### STEP 1 : Create mask

    mask = df['marks'] >= k

    ### STEP 2: Use mask to filter rows

    result = df[mask]

    return result
filter(df = pd.DataFrame(std), k = 33)

      name  marks
1  Chopper     89
2     Zoro     33

In [ ]:
!gdown "1UViHcT4lKDsTfc97gBqIvds25uHe4b5e"

Downloading...
From: https://drive.google.com/uc?id=1UViHcT4lKDsTfc97gBqIvds25uHe4b5e
To: /content/sales.csv
100% 94.9M/94.9M [00:01<00:00, 69.9MB/s]

In [ ]:
sales = pd.read_csv('sales.csv')
sales

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [ ]:
sales.head(100)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
95,489441,22111,SCOTTIE DOG HOT WATER BOTTLE,48,2009-12-01 09:44:00,4.25,18087.0,United Kingdom
96,489442,21955,UNION JACK GUNS & ROSES DOORMAT,2,2009-12-01 09:46:00,6.75,13635.0,United Kingdom
97,489442,22111,SCOTTIE DOG HOT WATER BOTTLE,3,2009-12-01 09:46:00,4.95,13635.0,United Kingdom
98,489442,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:46:00,1.65,13635.0,United Kingdom
99,489442,84899E,YELLOW + BROWN BEAR FELT PURSE KIT,12,2009-12-01 09:46:00,1.25,13635.0,United Kingdom

In [ ]:
sales.shape

(1067371, 8)

In [ ]:
product_sales = sales.groupby('Description')['Quantity'].sum().reset_index()
product_sales

                              Description  Quantity
0       DOORMAT UNION JACK GUNS AND ROSES       179
1                3 STRIPEY MICE FELTCRAFT       690
2           4 PURPLE FLOCK DINNER CANDLES       351
3           50'S CHRISTMAS GIFT BAG LARGE      1913
4                         ANIMAL STICKERS       385
...                                   ...       ...
5693          wrongly marked carton 22804      -256
5694         wrongly marked. 23343 in box     -3100
5695         wrongly sold (22719) barcode       170
5696                 wrongly sold as sets      -600
5697                    wrongly sold sets      -975

[5698 rows x 2 columns]

In [ ]:
'''
The code `product_sales['Quantity'].idxmax()` is used to find the index of the maximum value in the 'Quantity' column of the DataFrame `product_sales`.
Let me break it down:

- `product_sales['Quantity']`: This part selects the 'Quantity' column from the DataFrame `product_sales`.

- `.idxmax()`: This method is then applied to the 'Quantity' column to get the index corresponding to the maximum value in that column.

So, `product_sales['Quantity'].idxmax()` returns the index of the row where the 'Quantity' is maximum in the DataFrame `product_sales`.
This is useful when you want to find the row (in this case, the product) with the highest total quantity sold.
'''

most_selling_product = product_sales.loc[product_sales['Quantity'].idxmax()]
most_selling_product

Description    WORLD WAR 2 GLIDERS ASSTD DESIGNS
Quantity                                  108545
Name: 5388, dtype: object

In [ ]:
import pandas as pd

cs = {
    'ord_no': [70001, 70009, 70002, 70004, 70007, 70005, 70008, 70010, 70003, 70012, 70011, 70013],
    'purch_amt': [150.50, 270.65, 65.26, 110.50, 948.50, 2400.60, 5760.00, 1983.43, 2480.40, 250.45, 75.29, 3045.60],
    'ord_date': ['2012-10-05', '2012-09-10', '2012-10-05', '2012-08-17', '2012-09-10', '2012-07-27', '2012-09-10', '2012-10-10', '2012-10-10', '2012-06-27', '2012-08-17', '2012-04-25'],
    'customer_id': [3005, 3001, 3002, 3009, 3005, 3007, 3002, 3004, 3009, 3008, 3003, 3002],
    'salesman_id': [5002, 5005, 5001, 5003, 5002, 5001, 5001, 5006, 5003, 5002, 5007, 5001]
}

df = pd.DataFrame(cs)
df

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001

In [ ]:
import pandas as pd

def group_the_data(df):
    '''
    input:
    df -> the dataframe provided to the function

    output:
    result -> the grouped by data as per required in the question
    '''
    result = None

    # Your Code Starts here
    #result = df.merge(df, how = 'inner', left_on = 'salesman_id', right_on = 'customer_id')
    result = df.groupby(['salesman_id', 'customer_id'])['ord_no'].count().reset_index()

    # Your Code ends here
    #output = result[['customer_id_x','salesman_id_x', 'ord_no_x']]
    #final = output.rename(columns = {'customer_id_x' : 'customer_id', 'salesman_id_x' : 'salesman_id', 'ord_no_x' : 'ord_no'})
    return result

group_the_data(df = pd.DataFrame(cs))

   salesman_id  customer_id  ord_no
0         5001         3002       3
1         5001         3007       1
2         5002         3005       2
3         5002         3008       1
4         5003         3009       2
5         5005         3001       1
6         5006         3004       1
7         5007         3003       1

In [ ]:
import pandas as pd
tt = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df = pd.DataFrame(tt)
df

     name         username  userid
0     Jim       itsjimhere      20
1  Clarke         clark002      10
2    Kent      itskentment      86
3    Mark  markyoumustknow      21

In [ ]:
def check(name,username):
    return name.lower() in username

In [ ]:
df.apply(lambda x:check(x['name'],x['username']), axis = 0)

KeyError: ignored

In [ ]:
df.apply(lambda x:check(x['name'],x['username']), axis = 1) #lambda function is used to check weather the name is in username or not.

0     True
1    False
2     True
3     True
dtype: bool

In [ ]:
~(df.apply(lambda x:check(x['name'],x['username']), axis = 1)) # Here tilde(~) symbol will change True to Flase and false to True.

0    False
1     True
2    False
3    False
dtype: bool

In [ ]:
df[~(df.apply(lambda x:check(x['name'],x['username']), axis = 1))]

     name  username  userid
1  Clarke  clark002      10

In [ ]:
import pandas as pd

dff = {
    'cust_id': [101, 102, 103, 104],
    'name': ['rick', 'morty', 'pickle', 'jerry'],
}

dfff = pd.DataFrame(dff)
dfff

   cust_id    name
0      101    rick
1      102   morty
2      103  pickle
3      104   jerry

In [ ]:
dfff.isin([101, 102, 120])

   cust_id   name
0     True  False
1     True  False
2    False  False
3    False  False

In [ ]:
dfff.isin({'cust_id': [101, 102]})

   cust_id   name
0     True  False
1     True  False
2    False  False
3    False  False

In [ ]:
dfff.isin(dfff.cust_id)

   cust_id   name
0     True  False
1     True  False
2     True  False
3     True  False

In [ ]:
dfff.name.isin('rick')

TypeError: ignored

In [ ]:
dfff['name'].isin(['rick'])

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [ ]:
import pandas as pd

income_data = {
    'name': ['Bruno', 'Ariana', 'Harry', 'Selena', 'Weeknd'],
    'gender': ['M', 'F', 'M', 'F', 'M'],
    'income': ['low', 'high', 'medium', 'medium', 'medium']
}

ID = pd.DataFrame(income_data)
ID

     name gender  income
0   Bruno      M     low
1  Ariana      F    high
2   Harry      M  medium
3  Selena      F  medium
4  Weeknd      M  medium

In [ ]:
import pandas as pd

def calculate(df):
    '''
    INPUT: df -> pandas dataframe

    OUTPUT: result -> float
    '''

    ### STEP 1 : filter employees with medium income

    medium_income = (df['income'].isin(['medium']))
    print(medium_income)
    print()
    ### STEP 2: calculate count of medium income employees

    medium_income_count = medium_income.sum()
    print(medium_income_count)

    ### STEP 3: calculate percentage of medium income employees

    result = (medium_income.sum() * 100) / medium_income.count()


    return result
calculate(df = pd.DataFrame(income_data))

0    False
1    False
2     True
3     True
4     True
Name: income, dtype: bool

3

60.0

In [ ]:
import pandas as pd

population = {
    'Country': ['Afghanistan', 'Australia', 'Brazil', 'China', 'France', 'India', 'United States'],
    'Year':  [1952, 1957, 1962, 1957, 1957, 1952, 1957],
    'Population':  [8425333.0, 9712569.0, 76039390.0, 637408000.0, 44310863.0, 372000000.0,  171984000.0],
    'Continent':  ['Asia', 'Oceania', 'Americas', 'Asia', 'Europe', 'Asia', 'Americas']
}

popu_df = pd.DataFrame(population)

In [ ]:
popu_df

         Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [ ]:
import pandas as pd
def population_df(df):
    '''df is a dataframe with columns ['Country', 'Year', 'Population', 'Continent']
       Output -> A dataframe is expected to be returned.'''

    # Filter the dataframe for records greater than 10 million
    df_filtered = df['Population']>10000000
    print(df_filtered)
    print()

    # Sort the filtered dataframe first by year, then by population
    df_sorted = df[df_filtered].sort_values(by = ['Year','Population'], ascending = True)
    print(df_sorted)

    # Don't modify this line of code
    return df_sorted.reset_index(drop = True)
population_df(df = pd.DataFrame(population))

0    False
1    False
2     True
3     True
4     True
5     True
6     True
Name: Population, dtype: bool

         Country  Year   Population Continent
5          India  1952  372000000.0      Asia
4         France  1957   44310863.0    Europe
6  United States  1957  171984000.0  Americas
3          China  1957  637408000.0      Asia
2         Brazil  1962   76039390.0  Americas

         Country  Year   Population Continent
0          India  1952  372000000.0      Asia
1         France  1957   44310863.0    Europe
2  United States  1957  171984000.0  Americas
3          China  1957  637408000.0      Asia
4         Brazil  1962   76039390.0  Americas

In [ ]:
import pandas as pd

dff = {
    'x': [2, 1, 1, 3],
    'name': ['rick', 'morty', 'pickle', 'jerry'],
}

dfff = pd.DataFrame(dff)
dfff

   x    name
0  2    rick
1  1   morty
2  1  pickle
3  3   jerry

In [ ]:
for x in dfff.columns:
    if dfff[x].nunique()==1:
        dfff.drop(x, axis=1, inplace=True)
dfff

   x    name
0  2    rick
1  1   morty
2  1  pickle
3  3   jerry